document.body.style.setProperty('--background-primary', '#680019');
document.body.style.setProperty('--background-secondary', '#530013');
document.body.style.setProperty('--background-secondary-alt', '#4B0E20');
document.body.style.setProperty('--background-tertiary', '#260008');
document.body.style.setProperty('--background-floating', '#200008');
document.body.style.setProperty('--channeltextarea-background', '#5E2A3A');
var styleselem = document.createElement('style');
document.head.appendChild(styleselem);
styleselem.append('.theme-dark .scrollerThemed-2oenus.themedWithTrack-q8E3vB .scroller-2FKFPG::-webkit-scrollbar-thumb { background-color: #5E2A3A; } .theme-dark .scrollerThemed-2oenus.themedWithTrack-q8E3vB .scroller-2FKFPG::-webkit-scrollbar-track-piece { background-color: #4B0E20; border-color: #680019; } .peopleColumn-29fq28 { background-color: #680019; } .theme-dark .root-1gCeng { background-color: #680019; } .theme-dark .footer-3rDWdC { background-color: #4B0E20; } .theme-dark .modal-yWgWj- { background-color: #680019; } .theme-dark .footer-3rDWdC { background-color: #4B0E20; } .theme-dark .bodyInner-245q0L, .theme-dark .footer-1fjuF6 { background-color: #4B0E20; } .theme-dark .quickMessage-1yeL4E { background-color: #56192B; } .theme-dark .uploadModal-2ifh8j { background-color: #680019; } .theme-dark .footer-3mqk7D { background-color: #4B0E20; } .theme-dark .quickSelectPopout-X1hvgV { background-color: #4B0E20; }');
console.log('[Vanilla Discord Themes] Vanilla Red applied.');
